### ISSUE TITLE
Rename project to `simpleicons.vercel.app`?

### ISSUE THREAD

**Issue by LitoMore** [simpleicons/simpleicons.now.sh#155]
How about renaming this repository to `simpleicons.vercel.app`?

BTW, all documentations and project profiles need to be updated as well.

**Comment by LitoMore** [comment]
BTW, I can help to maintain this project.

**Comment by LitoMore** [comment]
Thanks. Feel free to send me an invitation to join your organization.

**Comment by LitoMore** [comment]
I created a new service due to this project is lack of maintenance.

See: https://github.com/simple-icons/simple-icons#cdn-with-colors
Source: https://github.com/LitoMore/simple-icons-cdn

**Comment by amio** [comment]
Great work!

Just updated the readme, thanks for reminding @LitoMore
